# Generated by Django 4.2.1 on 2023-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200, unique=True)),
                ("totalTests30", models.IntegerField(default=0)),
                ("totalTests50", models.IntegerField(default=0)),
                ("totalTests100", models.IntegerField(default=0)),
                ("totalTests150", models.IntegerField(default=0)),
                ("totalTests200", models.IntegerField(default=0)),
                ("totalTests30Sum", models.IntegerField(default=0)),
                ("totalTests50Sum", models.IntegerField(default=0)),
                ("totalTests100Sum", models.IntegerField(default=0)),
                ("totalTests150Sum", models.IntegerField(default=0)),
                ("totalTests200Sum", models.IntegerField(default=0)),
                ("best30", models.IntegerField(null=True)),
                ("best50", models.IntegerField(null=True)),
                ("best100", models.IntegerField(null=True)),
                ("best150", models.IntegerField(null=True)),
                ("best200", models.IntegerField(null=True)),
                ("results", models.TextField()),
            ],
        ),
    ]
