# Generated by Django 4.2.1 on 2023-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_mymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersdata",
            name="username",
            field=models.CharField(default="Hello", max_length=200, unique=True),
        ),
    ]
